#!/bin/bash

#Set these variables based on your own evironment
HADOOP_HOME=~/Hadoop/hadoop-0.20.203.0
MAHOUT_HOME=~/Hadoop/mahout/trunk
MAHOUT=${MAHOUT_HOME}/bin/mahout
HADOOP=${HADOOP_HOME}/bin/hadoop

USAGE="Usage: Re-Cluster
                         \t\t\t [{-h | --help}] \n
                         \t\t\t [{-c | --clusterHome} <clusterHome>] (default is user home dir) \n
                         \t\t\t [{-n | --numTopics} <numberOfTopics>] (default is 5) \n
    \tExample: Re-Cluster -c /data/Clustering -n 7 \n"

#variables passed in by arguments
CLUSTER_HOME=/user/`basename $HOME`
NUM_TOPICS=5

SHORTOPTS="hc:n:"
LONGOPTS="help,clusterHome:,numTopics:"
ARGS=`getopt -s bash --options=$SHORTOPTS  \
  --longoptions=$LONGOPTS --name=$PROGNAME -- "$@"`

eval set -- "$ARGS"

while true; do
    case $1 in
        -h|--help)
            echo -e $USAGE
            exit 0
            ;;
        -c|--clusterHome)
            shift
            CLUSTER_HOME=$1
            ;;
        -n|--numTopics)
            shift
            NUM_TOPICS=$1
            ;;
        --)
            shift
            break
            ;;
        *)
            shift
            break
            ;;
    esac
   # Throw away the '--' that's added by getopt.
   # The -- case above doesn't get hit when user
   # forgets to put in any required args.
   shift
done

#Remove old results
"$HADOOP" fs -rmr ${CLUSTER_HOME}/lda-results                                     
                            
#Perform LDA Clustering
"$HADOOP" jar ./target/Clustering-1.0-SNAPSHOT.jar  \
    --input     ${CLUSTER_HOME}/vectors/tf-vectors  \
    --output    ${CLUSTER_HOME}/lda-results         \
    --numTopics $NUM_TOPICS                         \
    --maxIter   25                                  

                            
